// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Instagram
{
    internal sealed partial class Vsix
    {
        public const string Id = "Instagram.dd908035-7856-4eaa-ad80-2296f4c35642";
        public const string Name = "Instagram";
        public const string Description = @"Instagram Web for Visual Studio is a creative extension that integrates Instagram Web directly into the Visual Studio IDE. Now you can stay connected with your Instagram feed, direct messages, and notifications, all while continuing to work on your development projects.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu Kumar Sharma HKS";
        public const string Tags = "";
    }
}
